version: '3.7'

services:
  api:
    image: registry.gitlab.com/devs_condominios/whatsapp:latest
    volumes:
      - .:/home/node
      - /home/node/node_modules
    environment:
      DATABASEURL: mongodb://BackEndAcesso:CcTf4iXoKd@api.acesso.srv.br:27017/Acesso?authMechanism=SCRAM-SHA-1&authSource=admin
      JWT_SECRET: MIHcAgEBBEIByH5ikLfv1qCK9wg6CtpfAapgdJsrYm7PoGmw7SPa/Vsw11afwpCf
    ports:
      - 3007:3007
    command: 'npm start'
    restart: always