version: '3'

services:
  api:
    image: wppapi
    volumes:
      - .:/home/node
      - /home/node/node_modules
    environment:
      DATABASEURL: mongodb://BackEndAcesso:CcTf4iXoKd@mongo:27017/Acesso?authMecanism=SCRAM-SHA-1&authSource=admin
      JWT_SECRET: MIHcAgEBBEIByH5ikLfv1qCK9wg6CtpfAapgdJsrYm7PoGmw7SPa/Vsw11afwpCf
    ports:
      - 3007:3007
    command: pm2-runtime 'npm start'
    depends_on: 
      - mongo
    restart: always
