'use strict';

module.exports = Object.freeze({
    APARTAMENTO_UNIDADE_HABITACIONAL: 1,
    VAGA_GARAGEM: 2,
    SALAO_DE_FESTAS: 3,
    PISCINA: 4,
    CHURRASQUEIRA: 5,
    SALA_REUNIÃO: 6,
    SAUNA: 7,
    ACADEMIA: 8,
    ELEVADOR: 9,

    INFO_UTIL: 15,

    CAMERA_CFTV: 20,
    INTERFONE: 21,
    DVR_NVR: 22,
    PORTEIRO_ELETRONICO: 23,
    LEITOR_IMPRESSAO_DIGITAL: 24,
    LEITOR_FACIAL: 25,
    PAINEL_INTEGRADO: 26,
    FECHADURA_ELETRICA: 27,
    MOTOR_PORTAO: 28,
    BOTOEIRA_ACIONAMENTO: 29,
    CENTRAL_TELEFONICA: 30,
    ATA_VOIP: 31,
    SWITCH_REDE: 32,
    RACK: 33,
    VIDEO_MONITOR: 34,
    BALOON_CFTV: 35,
    MICROFONE: 36,
    ACCESS_POINT_WIFI: 37,
    BOMBA_ELEVATORIA: 38,
    CERCA_ELETRICA: 39,
    CONTROLADORA: 40
});